services:

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Candy123

  pydantic:
    env_file:
      - .env
    build: 
        dockerfile: Dockerfile
        context: ./
    container_name: ollama-pydantic
    image: fullaware/ollama-pydantic:latest
    ports: 
        - "8000:8000"
    extra_hosts:
        - "host.docker.internal:host-gateway"